version: "3"
services:
  backend:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app:cached
    command: python manage.py runserver 0.0.0.0:8000
