version: "3"
services:
  backend:
    # environment:
    #   - PORT=8000
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app:cached
    # command: bash -c "python manage.py runserver 0.0.0.0:${PORT}"
    command: python manage.py runserver 0.0.0.0:8000
